function optim_signal = get_optim_signal(y_raw)
    y_den_0 = zeros(size(y_raw));
    options = optimoptions("fmincon", "Display", "iter-detailed", ...
        "OptimalityTolerance", 1e-10);
    optim_signal = fmincon(@(y_den)get_signal_distance(y_den,y_raw), ...
        y_den_0, [], [], [], [], [], [], [], ...
        options);
end