function rp_problem = get_rp_problem(cost_fun, ref, x0, lb, ub)
    cost_fun1 = cost_fun(1);
    cost_fun2 = cost_fun(2);
    dist_to_ref = @(x)norm([cost_fun1(x) - ref(1), cost_fun2(x) - ref(2)]);
    rp_problem.objective = dist_to_ref;
    rp_problem.x0 = x0;
    rp_problem.solver = 'fmincon';
    rp_problem.lb = lb;
    rp_problem.ub = ub;